### ISSUE TITLE
protocols.csv

### ISSUE THREAD

**Issue by toqueteos** [multiformats/go-multiaddr#1]
The current `protocols.csv` file uses tabs as separators instead of commas. This causes visual artifacts when it's [rendered by GitHub](https://github.com/jbenet/go-multiaddr/blob/master/protocols.csv).

Suggestions. Both should do the work:
1. Replace tabs for commas.
2. Rename file to `protocols.tsv` so it becomes a tab-separated file.

Reference: https://help.github.com/articles/rendering-csv-and-tsv-data

**Comment by lgierth** [comment]
Gonna remove protocols.csv here and point to the one in the multiaddr repo.
