### ISSUE TITLE
Reject empty multiaddrs

### ISSUE THREAD

**Issue by Stebalien** [multiformats/go-multiaddr#104]
These are almost always useless and can cause bugs like https://github.com/ipfs/go-ipfs/issues/6354.

However, this would break the marshaling code as that expects to be able to construct these. It also removes the base-case for a recursive multiaddr definition...

cc @hsanjuan, @lgierth thoughts?

**Comment by hsanjuan** [comment]
Nothing against it. Un-marshaling is impossible to do properly because `Multiaddr` is an interface and not a struct anyway. (#100 ). It might break my Multiaddr wrappers to handle that but fix would be easy.
