### ISSUE TITLE
panic: error registering dns4 protocol

### ISSUE THREAD

**Issue by hsanjuan** [multiformats/go-multiaddr#114]
Probably due to https://github.com/multiformats/go-multiaddr/commit/a088a4a5efa740ccc5f734ba43b722b064d4d02c ?

```
goroutine 1 [running]:
github.com/multiformats/go-multiaddr-dns.init.0()
        /go/pkg/mod/github.com/multiformats/go-multiaddr-dns@v0.0.3/dns.go:42 +0x33d
panic: error registering dns4 protocol: protocol by the name "dns4" already exists
```

@Stebalien

**Comment by Stebalien** [comment]
You have to _also_ update go-multiaddr-dns. I moved all the protocol definitions from external packages into this one so users don't have to, e.g., import the go-libp2p-circuit transport just to understand circuit addresses.

Unfortunately, I couldn't find a good non-breaking way to do this.

**Comment by hsanjuan** [comment]
Seems I got there because some deps use an older go-multiaddr-dns than what is required by the latest go-multiaddr. I'm not sure there's a clean way (artificially adding a dependency to go-multiaddr-dns here?)

**Comment by Stebalien** [comment]
Unfortunately, that would be a cyclic dependency.

We _could_ just _ignore_ conflicts for certain types (maybe even check the stack trace...) but that feels worse.

**Comment by Kubuxu** [comment]
@hsanjuan yes, the correct way is to run `go get github.com/multiformats/go-multiaddr-dns@latest` it will add an indirect dependency.

**Comment by hsanjuan** [comment]
Ok, put a better title in case other people land here. There's not much we can do other than the advice above.
