### ISSUE TITLE
Can listen support port reuse?

### ISSUE THREAD

**Issue by godcong** [multiformats/go-multiaddr#133]
Sometimes I need to make the same port for dial and listen.
Used to penetrate the network.
net.Listen makes my Dial not working

---------------------------------------------------------

May just need to change net.Listen => reuse.Listen

**Comment by Stebalien** [comment]
You can:

1. Use `DialArgs` to parse the multiaddr.
2. Listen with https://github.com/libp2p/go-reuseport.
3. Wrap the listener with `WrapNetListener`.
