### ISSUE TITLE
unix domain socket 

### ISSUE THREAD

**Issue by whyrusleeping** [multiformats/go-multiaddr#15]
would be neat if we could have multiaddrs to represent unix domain sockets

**Comment by jbenet** [comment]
yes would be nice.

```
/uds/path/to/sock
or
/unix/path/to/sock
```
? 

hard to tell --then-- when a uds addr ends without looking into the fs. opens up the door for certain attacks. It may be useful --ten-- to constrain the actual sock file (the last component member of uds to always say `.uds` or `.sock` or something. this is already typical, but making it _required_ would save us headaches.

**Comment by lgierth** [comment]
We already have `/unix`

**Comment by infinity0** [comment]
@lgierth how does one escape the slashes in a typical filepath?

`/unix/home/tcp/80/no/wait/my/username/really/is/tcp/honest/tcp/80`?

**Comment by Stebalien** [comment]
One does not. Unfortunately, `/unix` is currently a _terminal_ path. That is, everything after `/unix` is a path.

There are a bunch of discussions (e.g. https://github.com/multiformats/multiaddr/issues/63) in the mutliaddr repo trying to figure this out.
