### ISSUE TITLE
Registering new multicodecs

### ISSUE THREAD

**Issue by l0k18** [multiformats/go-multiaddr#151]
You can see here a wonderful, not-exported singleton registry variable that is in this delightful in-between where it's deprecated but functionality has not been maintained:

https://github.com/multiformats/go-multiaddr/blob/master/net/registry.go#L17

I get these deprecated markups in my IDE because the only way to add new codecs to this is marked deprecated, and it directs you to two functions *that depend on you first being able to **address** the aforementioned singleton registry variable*.

I only learned about this by looking at an old, not-updated uTP transport implementation. If it were my repository that singleton would be exported already, and the deprecation warnings would have some actual meaning. Or at least, to maintain some semblance of extensibility.

It's not that it's not extensible, it's just marked deprecated where you would extend it.

I figure first start the conversation, I am probably missing something as dealing with multiformats and libp2p involves a lotta lotta individual repositories which can be quite tedious to trace back and forth.

I am here mainly because I want to add a new protocol, namely https://github.com/xtaci/kcp and to do this it really needs to have kcp in there (yes I have already submitted a PR to add it to the CSV). This is day 3 of me tackling this project, I'm starting to make sense of it all but it's tricky.

I don't mind what way it gets resolved, for now I am just gonna smile at the strikethroughs in my syntax highlighting.

**Comment by Stebalien** [comment]
This was simply an oversight, not some complex bug: https://github.com/multiformats/go-multiaddr/pull/152.

Regardless, please lose the snark. First line of the [CoC](https://github.com/ipfs/community/blob/master/code-of-conduct.md#tldr): "Be respectful"
