### ISSUE TITLE
HTTP and HTTPS codes

### ISSUE THREAD

**Issue by toqueteos** [multiformats/go-multiaddr#2]
As specified on https://github.com/jbenet/multiaddr:

``````
Binary format:

(<1 byte proto><n byte addr>)+
<1 byte ipv4 code><4 byte ipv4 addr><1 byte udp code><2 byte udp port>
<1 byte ipv6 code><16 byte ipv6 addr><1 byte tcp code><2 byte tcp port>```
``````

Using just 1 byte won't work for HTTP (code: 480) and HTTPS (code: 443) because they are **out of bounds**.

**Comment by lgierth** [comment]
The code has long been a varint now, closing
