### ISSUE TITLE
Type mismatch in multiaddr.go

### ISSUE THREAD

**Issue by pdfinn** [multiformats/go-multiaddr#211]
## Problem Description

When building my Go application that uses `go-multiaddr` as a dependency, I encountered a type mismatch error at line 223 of `multiaddr.go`.

The full error message is as follows:

\# github.com/multiformats/go-multiaddr
../../../go/pkg/mod/github.com/multiformats/go-multiaddr@v0.10.1/multiaddr.go:223:25: type func(a Multiaddr, b Multiaddr) bool of func(a, b Multiaddr) bool {…} does not match inferred type func(a Multiaddr, b Multiaddr) int for func(a E, b E) int

## Steps to Reproduce

1. I am using `go-multiaddr` version `v0.10.1` in my Go application.
2. When I build my application with `go build`, the above error is thrown.

## Expected Behavior

I expected the application to build without any type mismatch errors.

## System Information

- Go version: go version go1.20.7 darwin/arm64
- Operating system and version: Mac OS 13.5

Please let me know if you need any further information. I am currently blocked by this issue and would appreciate any assistance or guidance.

Thank you!

**Comment by sukunrt** [comment]
Probably the same issue as https://github.com/multiformats/go-multiaddr/issues/208

Can you downgrade `golang.org/x/exp` and try?

**Comment by pdfinn** [comment]
Issue Resolution:

Downgrade `golang.org/x/exp`

Steps to Resolve:

I downgraded golang.org/x/exp to version v0.0.0-20230728194245-b0cb94b80691.
After downgrading, I tested the application to ensure that the problem was resolved and no other functionality was adversely affected.
The issue no longer appears with the downgraded version.
