### ISSUE TITLE
Is HTTP a path protocol?

### ISSUE THREAD

**Issue by keks** [multiformats/go-multiaddr#37]
[protocol.go:15](https://github.com/multiformats/go-multiaddr/blob/master/protocols.go#L15) says that `Protocol.Path` "indicates a path protocol (eg unix, http)". However, the value is `false` for the HTTP protocol struct. Is that on purpose?

**Comment by VictorBjelkholm** [comment]
Let's define it here: https://github.com/multiformats/multiaddr/issues/63
