### ISSUE TITLE
Strangest things with github.com/jbenet/go-multiaddr and github.com/multiformats/go-multiaddr

### ISSUE THREAD

**Issue by kpmy** [multiformats/go-multiaddr#39]
For now, go-ipfs and subpackages use jbenet/go-multiaddr, but libp2p imports multiformats/go-multiaddr, so when trying to compile libp2p/examples two of this go-multiaddr get in conflict and give strange output.

**Comment by lgierth** [comment]
We moved a few of the multi* repos from individual accounts to the multiformats organization, and that broke a few things :( I'm working on fixing it and it should be all clear in the next couple of hours.

**Comment by RichardLitt** [comment]
@lgierth What do you think about helping me set up a bot to fix all broken links in a given organization's repos? That would fix this.

**Comment by lgierth** [comment]
The rewriting-the-links thing I already have locally, right now I'm working on automating the cascading gx package updates. This time the gx updates are finally massive and annoying enough to fully and properly automate it.

**Comment by RichardLitt** [comment]
@lgierth So you don't think a bot that would automatically PR broken GitHub links on moving a repo would be a good idea?

**Comment by lgierth** [comment]
It's just that the job is actually really complex -- it involves changes to code, releasing updated packages, etc. I'm not sure a bot will help since the act of find+replace is by far the smallest, and my text editor already automates that pretty well. What did you have in mind?

**Comment by RichardLitt** [comment]
@lgierth Hmm. Fair. Don't worry about it, I'll set it up - I need this for more than just updating packages, as that is specific. Having a s/// for GitHub repos would be super useful for README editing, and may be a tool I should just make.

**Comment by kpmy** [comment]
Github redirects /jbenet/go-multiaddr to /multiformats/go-multiaddr and this makes 'go get' to be 'go crazy get' :(

**Comment by RichardLitt** [comment]
@kpmy Has this been fixed? Just checking, since this was closed - want to make sure it's not being closed just because we haven't responded, but that we've actually fixed the issue. :)

**Comment by lgierth** [comment]
IIRC this is the last time we saw this transition issue
