### ISSUE TITLE
Why is there a protocols.csv in this repo?

### ISSUE THREAD

**Issue by marten-seemann** [multiformats/go-multiaddr#49]
This file is never parsed, and it seems to be outdated compared to the one in https://github.com/multiformats/multiaddr/.

**Comment by whyrusleeping** [comment]
We explain why here: https://github.com/multiformats/go-multiaddr/blob/master/protocols.go#L19

But yeah, it is mildly outdated compared to the one you linked

**Comment by marten-seemann** [comment]
This only explains why there shouldn't be a csv in this repo.

**Comment by whyrusleeping** [comment]
touche
