### ISSUE TITLE
0 port

### ISSUE THREAD

**Issue by CMCDragonkai** [multiformats/go-multiaddr#51]
In the test cases, 0 port is allowed for UDP, SCTP and TCP.

What's the reason for this? The 0 port is used for binding to a system allocated port, and it is also officially reserved by IANA and not be used for TCP or UDP messages.

If it this is allowed, then why does the onion test disallow a 0 port. 

I'm writing a haskell version of this library, and seeing these 2 testcases means I would have to split the port logic to allow 0 for certain protocols and disallow 0 for other protocols.

In the broader case, why would 0 ever be used in a multiaddress? I would think it is intended for the binding on the server side, but never passed around as an actually addressable resource, since it doesn't make sense for the system to randomly allocate a connecting port on the client side.

**Comment by lgierth** [comment]
> If it this is allowed, then why does the onion test disallow a 0 port.

I don't think 0-means-random-port works with Tor/Onion. Please correct me if I'm wrong.

> In the broader case, why would 0 ever be used in a multiaddress? I would think it is intended for the binding on the server side, but never passed around as an actually addressable resource

Correct

**Comment by CMCDragonkai** [comment]
@lgierth That's why I'm thinking that the 0 port should be disallowed in TCP and UDP. And this would unify the port parsing logic in my multiaddr library.

**Comment by lgierth** [comment]
port 0 is a legitimate use on the listening side. Not going to remove it :)

**Comment by CMCDragonkai** [comment]
Are services allowed to `bind` to a multiaddr? If so, then yes it makes sense to have a 0 port.

If onion addresses is part of multiaddr, then why isn't it possible to bind to a 0 port onion address?

Where in the docs does it say that onion addresses cannot have a 0 port?

**Comment by lgierth** [comment]
> Are services allowed to bind to a multiaddr? If so, then yes it makes sense to have a 0 port.

Correct

> If onion addresses is part of multiaddr, then why isn't it possible to bind to a 0 port onion address?

Port 0 is part of the OS's TCP/IP stack, and I guess Tor hidden services just don't provide such a functionality. One could emulate it within go-multiaddr, but that would be hard to pull off without race conditions.

> Where in the docs does it say that onion addresses cannot have a 0 port?

I don't know -- ping @david415 @ianopolous

**Comment by CMCDragonkai** [comment]
Implemented in haskell
