### ISSUE TITLE
En/decapsulate example is not working

### ISSUE THREAD

**Issue by hayarobi** [multiformats/go-multiaddr#67]
The example code in README.md
m.Decapsulate(ma.NewMultiaddr("/udp")) 
is result to fail in master/HEAD

I got two rocks; one is that he method NewMultiaddr returns multi values, but this is not the problem since I can go around this. The scond one is NewMultiaddr requires valid address, so calling ma.NewMultiaddr("/udp") will return error in runtime. I can’t find suitable walkaround yet.

**Comment by Stebalien** [comment]
So, `Decapsulate` was supposed to be the inverse of `Encapsulate`. That is:

```go
m1 := NewMultiaddr("/ip4/1.2.3.4/tcp/80")
m2 := m1.Decapsulate("/tcp/80")
// m2 == "/ip4/1.2.3.4"
```

However, the documentation is obviously incorrect (and I can't remember if it even works). I have a fix here: https://github.com/multiformats/go-multiaddr/pull/62 but this PR is a bit stuck in limbo.

The current "correct" (albeit a bit slow...) way to do what you want to do is to use `Split` and then iterate through the pieces. That is:

```go
pieces := Split(m)
for i, mi := range pieces {
    if mi.Protocols()[0] == P_UDP {
        return Join(pieces[:i]...)
    }
}
```

(or something like that)

---

(but yes, this is a documentation bug and a missing feature)

**Comment by overbool** [comment]
@hayarobi 
1. The `/udp` in `ma.NewMultiaddr("/udp")` should require an address.
2. `NewMultiaddr()` return two values, `Multiaddr` and `error`

@Stebalien could you please help me review my pr?
