### ISSUE TITLE
What about releasing a new version?

### ISSUE THREAD

**Issue by soupdiver** [multiformats/go-multiaddr#70]
I try to integrate https://github.com/ipfs/go-ipfs-api into a project. That repo depends on https://github.com/multiformats/go-multiaddr-net and that one on this.
I'm using `dep` as a package manager.
Installing all the dependencies results in code that does not compile.

It seems `dep` uses the latest release you have created, which is ~4 years old. Is there a reason why you haven't created a new release in all this time? If not, it would help to keep compatibility with other dependency management tools

**Comment by Stebalien** [comment]
Fair enough. We use `gx` internally but yes, we should also be tagging git releases.

**Comment by Stebalien** [comment]
Done.

**Comment by soupdiver** [comment]
❤️ 

thanks for adding to the other repos as well 👍
