### ISSUE TITLE
New release needed -- 1.2.7 does not have required NewTranscoderFromFunctions change

### ISSUE THREAD

**Issue by strobus** [multiformats/go-multiaddr#76]
1.2.7 does not contain the latest change to the method signature of NewTranscoderFromFunctions. This causes libraries like go-multiaddr-dns to break. [See line 47 of dns.go](https://github.com/multiformats/go-multiaddr-dns/blob/78f39e8892d4f8c5c9f18679cc06d0b40ecab8cf/dns.go#L47).

Could the maintainers please issue a new release that includes the change to the interface?

**Comment by Stebalien** [comment]
Fixed.
