### ISSUE TITLE
ValueForProtocol() and multiple occurences of same protocol

### ISSUE THREAD

**Issue by lgierth** [multiformats/go-multiaddr#83]
There can be multiple occurences of the same protocol in one multiaddr. Example that's already happening: `/ipfs/QmRelay/p2p-circuit/ipfs/QmRelay`

`Protocols()` looks like it can handle it, but `ValueForProtocol()` will only return the first occurence.

**Comment by Stebalien** [comment]
https://github.com/multiformats/go-multiaddr/pull/81/files#diff-e2cd38f38509c9033189fbf0317e414eR46

**Comment by lgierth** [comment]
You code faster than your own shadow, Sir.
