### ISSUE TITLE
why use "ipfs" instead of "p2p" as the Name in the code below? 

### ISSUE THREAD

**Issue by zhizouxiao** [multiformats/go-multiaddr#85]
the code is in the file `protocols.go`
``` golang
protoP2P = Protocol{
	Name:       "ipfs",
	Code:       P_P2P,
	VCode:      CodeToVarint(P_P2P),
	Size:       LengthPrefixedVarSize,
	Transcoder: TranscoderP2P,
}
```

**Comment by lanzafame** [comment]
It is currently being transitioned, see [here](https://github.com/multiformats/go-multiaddr/blob/393301199b4437234bd500b78bdf9555f6428c18/protocol.go#L53-L64)

**Comment by zhizouxiao** [comment]
@lanzafame thanks, It's very helpful. I'll close this issue now.
