### ISSUE TITLE
Implement flag.Value interface

### ISSUE THREAD

**Issue by bigs** [multiformats/go-multiaddr#97]
The [flag.Value](https://golang.org/pkg/flag/#Value) interface allows different types to be parsed by the built in `flag` module. Even though said module isn't great, adding the `Set` method would make things easier for anyone wishing to parse mutliaddrs.

**Comment by bigs** [comment]
Errrrrrrrrrrr... closing this, as it's not possible given our hidden implementation.

**Comment by Kubuxu** [comment]
@bigs what do you mean?

**Comment by bigs** [comment]
`Set` relies on being able to instantiate a zero-multiaddr, which we don't at the moment, because it would be invalid (and panic if access was attempted). if you can think of a decent way of getting around this, i'd love to implement it! i'm just not sure off hand which way to go is preferable.

**Comment by Kubuxu** [comment]
Could it work with nil pointer?
